name: Build MangaPro extension

on:
  push:
    branches:
      - clean-mangapro
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK (command-line tools + platform)
        # r0adkll/setup-android is a widely used action to install SDK/platforms
        uses: r0adkll/setup-android@v2
        with:
          api-level: 33
          build-tools: "33.0.2"
          components: "platform-tools,build-tools;33.0.2,platforms;android-33"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build (assembleDebug for the mangapro module)
        run: ./gradlew :src:ar:mangapro:assembleDebug --no-daemon
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mangapro-apk
          path: src/ar/mangapro/build/outputs/**/*.apk
