name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build MangaPro only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build MangaPro only
        run: ./gradlew :src:ar:mangapro:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mangapro-apk
          path: src/ar/mangapro/build/outputs/apk/release/*.apk
